/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AddPlatform: typeof import('./src/components/platforms/addPlatform.vue')['default']
    AssistantSetting: typeof import('./src/components/defaultModel/assistantSetting.vue')['default']
    DefaultModel: typeof import('./src/components/defaultModel/index.vue')['default']
    DiffViewer: typeof import('./src/components/DiffViewer/index.vue')['default']
    DocxPreview: typeof import('./src/components/office/docxPreview.vue')['default']
    File: typeof import('./src/components/file/index.vue')['default']
    FileClass: typeof import('./src/components/preview/fileClass.vue')['default']
    FileSvg: typeof import('./src/components/fileClass/fileSvg.vue')['default']
    FileTree: typeof import('./src/components/vscode/fileTree.vue')['default']
    FullPreview: typeof import('./src/components/preview/fullPreview.vue')['default']
    Image: typeof import('./src/components/browser/image.vue')['default']
    ImgModal: typeof import('./src/components/file/imgModal.vue')['default']
    Lang: typeof import('./src/components/lang/index.vue')['default']
    LeftRight: typeof import('./src/components/menu/LeftRight.vue')['default']
    Logo: typeof import('./src/components/logo.vue')['default']
    Markdown: typeof import('./src/components/markdown/index.vue')['default']
    McpServer: typeof import('./src/components/mcpServer/index.vue')['default']
    MessageFileList: typeof import('./src/components/MessageFileList/index.vue')['default']
    Modelinfo: typeof import('./src/components/platforms/modelinfo.vue')['default']
    ModelsList: typeof import('./src/components/platforms/modelsList.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Office: typeof import('./src/components/preview/office.vue')['default']
    OfficePreview: typeof import('./src/components/file/officePreview.vue')['default']
    PdfPreview: typeof import('./src/components/office/pdfPreview.vue')['default']
    Preview: typeof import('./src/components/preview/index.vue')['default']
    ProfileNotification: typeof import('./src/components/ProfileNotification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchEngine: typeof import('./src/components/searchEngine/index.vue')['default']
    SearchResults: typeof import('./src/components/browser/searchResults.vue')['default']
    SelectModel: typeof import('./src/components/defaultModel/selectModel.vue')['default']
    ServerList: typeof import('./src/components/mcpServer/ServerList.vue')['default']
    ServerSettings: typeof import('./src/components/mcpServer/ServerSettings.vue')['default']
    SettingPlatform: typeof import('./src/components/platforms/settingPlatform.vue')['default']
    SiderTerminal: typeof import('./src/components/terminal/siderTerminal.vue')['default']
    TaskIcon: typeof import('./src/components/menu/TaskIcon.vue')['default']
    Terminal: typeof import('./src/components/terminal/index.vue')['default']
    TopicNaming: typeof import('./src/components/defaultModel/TopicNaming.vue')['default']
    Translation: typeof import('./src/components/defaultModel/translation.vue')['default']
    User: typeof import('./src/components/menu/User.vue')['default']
    Video: typeof import('./src/components/browser/video.vue')['default']
    Vscode: typeof import('./src/components/vscode/index.vue')['default']
    XlsxPreview: typeof import('./src/components/office/xlsxPreview.vue')['default']
  }
}
